docs/source/usage/convert.rst
=> ✏️ fix typo

docs/source/usage/inventory.rst, fotoobo/helpers/log.py, tests/fotoobo.yaml, tests/helpers/test_log.py
After we reworked the logging configuration there are now also more tests, especially for our SysLogFormatter.
=> Add more tests to logs

CHANGELOG.md, docs/source/code.rst, docs/source/usage/inventory.rst, fotoobo/inventory/inventory.py, pyproject.toml, tests/data/inventory.yaml, tests/inventory/test_inventory.py
Add `globals` section to the inventory to add device specific global options
closes #48
=> Add globals section to inventory

tests/helpers/test_log.py
=> ✅ fix timezoning, closes #68

CHANGELOG.md, docs/source/usage/getting_started.rst
=> 📝 Adjust "Getting started"

CHANGELOG.md, docs/source/usage/configuration.rst, docs/source/usage/getting_started.rst, fotoobo.yaml.sample, fotoobo/cli/fgt/main.py, fotoobo/helpers/config.py, fotoobo/utils/fgt/main.py, test_fgt_1.conf, tests/helpers/test_config.py, tests/utils/fgt/test_backup.py
=> 👔 🔧 Remove backup_dir from fotoobo.yaml

fotoobo/inventory/inventory.py
expanded_inventory_file = os.path.expanduser(self._inventory_file)
=> Expand inventory path to accept shortcut '~' character

CHANGELOG.md, docs/source/usage/inventory.rst, fotoobo.yaml.sample, fotoobo/fortinet/fortinet.py, fotoobo/helpers/config.py
=> :sparkles: Add possibility to use a custom CA instead of ssl_verify=false

fotoobo/helpers/log.py, tests/helpers/test_log.py
=> :bug: no traceback.log on unresolvable/unreachable syslog server 

CHANGELOG.md, docs/source/code.rst, docs/source/index.rst, docs/source/usage/import_fotoobo.rst
=> 📝 add documentation about how to import and use fotoobo into python

fotoobo/cli/ems/monitor_commands.py, fotoobo/fortinet/forticlientems.py, fotoobo/helpers/files.py, fotoobo/helpers/result.py, tests/helpers/test_files.py
Still have to do the documentation
=> Move EMS templating to the results class

CHANGELOG.md, fotoobo/cli/ems/get_commands.py, fotoobo/cli/fgt/main.py, fotoobo/cli/fgt/monitor_commands.py, fotoobo/cli/fmg/get_commands.py, fotoobo/helpers/output.py, fotoobo/helpers/result.py, fotoobo/tools/fmg/get.py, tests/helpers/test_output.py, tests/helpers/test_results.py, tests/tools/fgt/monitor/test_hamaster.py, tests/tools/fmg/get/test_adoms.py, tests/tools/fmg/get/test_devices.py, tests/tools/fmg/get/test_policy.py, tests/tools/fmg/get/test_version.py
Any logic to print something to the console or write it into a file has been moved to the CLI classes. This lays the ground to add a REST API frontend to fotoobo sometime in the future.
closes #101
=> All tools [returning something] now use the Result class

WHATSNEW.md, docs/source/usage/import_fotoobo.rst, docs/source/usage/inventory.rst, fotoobo/fortinet/fortimanager.py, fotoobo/tools/fmg/get.py, tests/data/test_fmg.key, tests/fortinet/test_fortimanager.py
=> ⚡️ 🎨 Improve FMG/FAZ session handling

README.md, WHATSNEW.md
Now the logo is also displayed on PyPI
closes #143
=> 📝 Update logo path in README

docs/source/developer/architecture/1_introduction_goals.rst, docs/source/developer/architecture/4_solution_strategy.rst, docs/source/developer/architecture/5_building_block_view.rst, docs/source/developer/architecture/8_quality_requirements.rst, docs/source/developer/architecture/9_risks_technical_depths.rst, docs/source/developer/architecture_documentation.rst, docs/source/developer/c4.rst, docs/source/developer/how_to/fortinet/fortigate/fortigate_config.rst, docs/source/usage/configuration.rst, docs/source/usage/fortigate_config_check.rst, docs/source/usage/getting_started.rst, docs/source/usage/import_fotoobo.rst, docs/source/usage/inventory.rst
- always write **fotoobo** in bold and lowercase
- Fix some broken or wrong links
- Update formatting => no subnumberings in architecture documentation
- Fix error in FortiGate configuration check
=> Fixes in documentation

CHANGELOG.md, WHATSNEW.md, fotoobo/__init__.py, pyproject.toml
=> :bookmark: Commit version v1.1.0

WHATSNEW.md, pyproject.toml
Added some classifiers. Feel free to start discussion.
Also added:
- `license = "LGPL-3.0-only"`
- `repository = "https://github.com/migros/fotoobo"`
closes #162
=> Add classifiers to pyproject.toml #162

docs/source/usage/configuration.rst, fotoobo/helpers/config.py, tests/helpers/test_config.py
=> 🔐 Read vault secrets from environment

.github/workflows/tests.yaml, CHANGELOG.md, WHATSNEW.md, docs/source/usage/configuration.rst, fotoobo.yaml.sample, fotoobo/__init__.py, fotoobo/fortinet/fortinet.py, fotoobo/helpers/config.py, fotoobo/helpers/vault.py, pyproject.toml, tests/helpers/test_vault.py
=> Traceback on vault certificate error #174

docs/source/developer/c4.rst
=> 📝 Minor fixes

fotoobo/helpers/config.py
It seems my former pull request https://github.com/migros/fotoobo/pull/182 was deleted due to some cleanup tasks. So here it is again.
=> 🩹 Make config_file option really optional

.github/workflows/create-github-release.yaml, .github/workflows/publish-to-pypi.yaml, .github/workflows/tests.yaml, WHATSNEW.md
Updated actions to latest major version
Also fixed the mypy artifact name due to a new restriction where an artifact may not be overwritten anymore: https://github.com/actions/upload-artifact/issues/471#issuecomment-1863085550
Closes #189
=> Node.js deprecation warning #189

WHATSNEW.md, fotoobo/cli/fgt/config_commands.py, fotoobo/helpers/result.py, tests/cli/fgt/test_cli_fgt_config_check.py
=> 👔 Add option --smtp to `fgt config check`

WHATSNEW.md, fotoobo/fortinet/fortinet.py, tests/fortinet/test_fortianalyzer.py, tests/fortinet/test_forticlientems.py, tests/fortinet/test_fortimanager.py, tests/fortinet/test_fortinet.py
=> Make fortinet.api method more generic #194

CHANGELOG.md, WHATSNEW.md, fotoobo/__init__.py, pyproject.toml
=> Release version v2.1.1

WHATSNEW.md, fotoobo/helpers/config.py, tests/helpers/test_config.py
=> 🐛 Better error handling when loading logging configuration
